// GENERATED from the matrix declarations, then checked by coverage.test.tsx.
// It exists because the gallery is a SERVER component: importing the specs
// there would pull every design-system component (three.js included) into an
// index page that renders none of them. Plain numbers cross that boundary
// for free, and the test fails the moment they stop matching the specs.
export const COMPONENT_COUNTS: Record<string, { variants: number; states: number }> = {
  'accordion': { variants: 3, states: 2 },
  'alert': { variants: 4, states: 0 },
  'artifact': { variants: 3, states: 0 },
  'avatar': { variants: 6, states: 1 },
  'badge': { variants: 8, states: 0 },
  'bento-grid': { variants: 3, states: 0 },
  'burst': { variants: 2, states: 0 },
  'button': { variants: 8, states: 8 },
  'card': { variants: 4, states: 0 },
  'checkbox': { variants: 3, states: 6 },
  'suggestion': { variants: 3, states: 3 },
  'tabs': { variants: 3, states: 2 },
  'choice-card': { variants: 3, states: 7 },
  'collapsible': { variants: 5, states: 3 },
  'combobox': { variants: 3, states: 0 },
  'corner-markers': { variants: 4, states: 0 },
  'cube': { variants: 3, states: 0 },
  'table-data': { variants: 2, states: 0 },
  'date-range-picker': { variants: 4, states: 3 },
  'drawer': { variants: 2, states: 0 },
  'empty-state': { variants: 4, states: 0 },
  'footer': { variants: 3, states: 0 },
  'chart-funnel': { variants: 2, states: 0 },
  'gauge': { variants: 4, states: 0 },
  'heat-grid': { variants: 6, states: 0 },
  'icon-button': { variants: 6, states: 8 },
  'input': { variants: 6, states: 5 },
  'item': { variants: 5, states: 6 },
  'logo-cloud': { variants: 2, states: 1 },
  'marquee': { variants: 3, states: 0 },
  'media-card': { variants: 6, states: 0 },
  'message': { variants: 3, states: 1 },
  'music-player': { variants: 7, states: 0 },
  'navbar': { variants: 3, states: 0 },
  'nav-item': { variants: 7, states: 6 },
  'nodes': { variants: 2, states: 0 },
  'orb': { variants: 1, states: 0 },
  'panel-header': { variants: 2, states: 0 },
  'panel-menu': { variants: 3, states: 1 },
  'planet': { variants: 2, states: 0 },
  'popover': { variants: 3, states: 0 },
  'progress-bar': { variants: 5, states: 0 },
  'prompt-input': { variants: 3, states: 1 },
  'chart-metric': { variants: 2, states: 0 },
  'chart-radar': { variants: 2, states: 0 },
  'radio': { variants: 3, states: 7 },
  'search-field': { variants: 4, states: 1 },
  'section-heading': { variants: 4, states: 0 },
  'pricing-card': { variants: 3, states: 0 },
  'strength-meter': { variants: 3, states: 0 },
  'segmented-control': { variants: 5, states: 0 },
  'sidebar': { variants: 5, states: 0 },
  'skeleton': { variants: 2, states: 0 },
  'slider': { variants: 5, states: 3 },
  'spinner': { variants: 4, states: 0 },
  'stat-tile': { variants: 5, states: 0 },
  'stepper': { variants: 3, states: 0 },
  'table-basic': { variants: 3, states: 2 },
  'tag': { variants: 5, states: 3 },
  'textarea': { variants: 4, states: 5 },
  'toggle': { variants: 2, states: 5 },
  'tool': { variants: 5, states: 2 },
  'tooltip': { variants: 4, states: 0 },
  'top-bar': { variants: 3, states: 0 },
  'chart-trend': { variants: 4, states: 0 },
  'user-card': { variants: 4, states: 0 },
  'user-menu': { variants: 4, states: 0 },
  'waveform': { variants: 4, states: 0 },
}
