#!/usr/bin/env node
/**
 * inject-premium.mjs — pulls closed-source premium components from the PRIVATE
 * source into this (public) build, so they can be served gated. Runs FIRST in
 * the dev/build chain. See AGENTS.md in the aicanvas-premium repo.
 *
 * Source resolution (in order):
 *   1. PREMIUM_LOCAL_PATH  — a local checkout of aicanvas-premium (dev / offline)
 *   2. GITHUB_PAT_PREMIUM  — HTTPS + read-only PAT shallow-clone (Vercel)
 *   3. neither             — skip cleanly (public forks build free-only)
 *
 * It copies each manifest component into the GITIGNORED components-workspace-premium/,
 * STRIPPING the premium marker (served code must be clean), writes
 * registry-data/_premium.json (feeds the gate's premiumSlugs), and generates the
 * gitignored app/lib/premium-registry.generated.tsx registration shim.
 *
 * It ALSO injects design-system material authored in the vault:
 *   - `systems`              whole tree per slug → that DESIGN_SYSTEMS entry's
 *                            rootDir (gitignored, e.g. design-systems/andromeda-pro/)
 *   - `freeSystemComponents` per-file lane into Andromeda LEGACY's committed
 *                            tree (design-systems/andromeda/components/)
 * and always writes the gitignored app/lib/andromeda-v2.generated.tsx (Andromeda
 * Legacy's bridge for the vault-authored free-lane components) and the Andromeda
 * Pro shims (app/lib/andromeda-pro*.generated.tsx: components + tokens, helpers,
 * template compositions): real re-exports when injected, the committed Legacy
 * tree or placeholder panels on degraded builds, so a fork with no vault still
 * compiles and renders.
 */
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, readdirSync, statSync, cpSync } from 'node:fs'
import { join, dirname, resolve } from 'node:path'
import { execSync } from 'node:child_process'
import { FREE_DS_PLACEHOLDER_SENTINEL, DESIGN_SYSTEMS } from './lib/design-systems.config.mjs'

const ROOT = process.cwd()
const TARGET = join(ROOT, 'components-workspace-premium')
const SHIM = join(ROOT, 'app/lib/premium-registry.generated.tsx')
// Andromeda LEGACY's free-lane bridge — production contract, name unchanged:
// app/_lib/andromeda/andromeda-demos.tsx and
// app/design-systems/andromeda/system/AndromedaShowcase.tsx import the 6
// free-lane names from it and must never be edited to point elsewhere.
const V2_SHIM = join(ROOT, 'app/lib/andromeda-v2.generated.tsx')
// Andromeda PRO's own shims — separate slug, separate files.
const V2_PRO_SHIM = join(ROOT, 'app/lib/andromeda-pro.generated.tsx')
const V2_PRO_EXAMPLES_SHIM = join(ROOT, 'app/lib/andromeda-pro-examples.generated.tsx')
const V2_PRO_HELPERS_SHIM = join(ROOT, 'app/lib/andromeda-pro-helpers.generated.tsx')
const BRAIN_TEASER_MODULE = join(ROOT, 'app/lib/andromeda-brain-teaser.generated.ts')
const BRAIN_TEASER_PRO_MODULE = join(ROOT, 'app/lib/andromeda-pro-brain-teaser.generated.ts')
const REGISTRY_DATA = join(ROOT, 'registry-data')
const PREMIUM_JSON = join(ROOT, 'registry-data/_premium.json')
const PREMIUM_LOCK = join(ROOT, 'premium.lock.json')
const BUILD_INFO = join(ROOT, 'app/lib/premium-build-info.generated.ts')

// The EXACT premium commit this public tree builds against (tracked in the public
// repo, bumped only by `npm run publish-premium`). The PAT/Vercel path checks out
// THIS sha instead of floating `main`, making every production build reproducible.
// Dev (PREMIUM_LOCAL_PATH) ignores the pin and uses your working checkout as-is.
let pinnedSha = ''
try {
  pinnedSha = String(JSON.parse(readFileSync(PREMIUM_LOCK, 'utf8')).sha || '').trim()
} catch {
  pinnedSha = ''
}

// The PUBLIC app commit this build is built FROM — a different axis from the
// premium sha/pinnedSha above (those track the vault pin). Captured HERE, at
// BUILD time, deliberately: Vercel always sets VERCEL_GIT_COMMIT_SHA in the build
// environment, whereas reading it at RUNTIME in the health route would depend on
// the project's "expose System Environment Variables" setting. If that setting is
// off, the field would be null forever and the deploy check would silently never
// run — worse than no check, because it looks like one. git rev-parse is the
// fallback (Vercel builds from a real clone); null when neither is available.
let appSha = String(process.env.VERCEL_GIT_COMMIT_SHA || '').trim()
if (!appSha) {
  try {
    appSha = execSync('git rev-parse HEAD', {
      cwd: ROOT,
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim()
  } catch {
    appSha = ''
  }
}

// Stamp what actually got injected into a gitignored const the /api/premium/health
// route imports — so prod can PROVE it is serving the intended premium commit,
// and (via appSha) the intended APP commit.
function writeBuildInfo(sha) {
  writeFileSync(
    BUILD_INFO,
    [
      '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
      'export const PREMIUM_BUILD = {',
      `  sha: ${JSON.stringify(sha || null)},`,
      `  pinnedSha: ${JSON.stringify(pinnedSha || null)},`,
      `  appSha: ${JSON.stringify(appSha || null)},`,
      '} as const',
      '',
    ].join('\n'),
  )
}
// Built from parts so THIS (tracked, public) file never contains the literal
// marker — otherwise the leak guard would flag inject-premium.mjs itself.
const MARKER = ['AICANVAS', 'PREMIUM', 'DO', 'NOT', 'COMMIT'].join('-')

function stripMarkerBlock(text) {
  let stripping = false
  return text.split('\n').filter((line) => {
    if (line.includes(MARKER)) {
      stripping = true
      return false
    }
    if (stripping && /^\s*\/\//.test(line)) return false
    stripping = false
    return true
  }).join('\n')
}

const log = (m) => console.log('[inject-premium] ' + m)

// Always leave a shim behind (empty when no premium) so component-registry.tsx's
// guarded require() resolves on forks / free-only builds.
function writeStubShim() {
  writeFileSync(
    SHIM,
    [
      '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored.',
      "import type { ComponentEntry } from './component-registry'",
      'export const PREMIUM_COMPONENTS: ComponentEntry[] = []',
      '',
    ].join('\n'),
  )
}

// ── Free v2 design-system components (manifest key `freeSystemComponents`) ──
// v2 DS components are authored in the vault but FREE for users: injected into
// design-systems/<system>/components/ so the public harness (showcase, demos,
// per-component pages, registry) treats them exactly like committed v1 files —
// but they are never committed to public git (git info/exclude below; the
// check-no-premium-leak guard is the backstop).

// Fallback export list for the generated Andromeda v2 shim. App client code
// (AndromedaShowcase, andromeda-demos) statically imports these names from the
// shim, so the shim MUST export them on EVERY run — including degraded builds
// where no vault (or an older pinned vault without `freeSystemComponents`) is
// reachable and nothing gets injected. In that case each fallback name becomes
// a placeholder component instead of a real re-export. UPDATE this list when a
// new v2 component ships (it mirrors the vault manifest's
// freeSystemComponents.andromeda).
const V2_FALLBACK_NAMES = ['MetricChart', 'Gauge', 'Waveform', 'MediaCard', 'DataTable', 'MusicPlayer']

// Export names the app imports from the generated v2 shim that the COMMITTED v1
// tree has no file for. On an injected build they arrive with their component;
// on a degraded build each becomes a placeholder panel so a fork still compiles.
// Mostly v2-only components, plus the two subcomponents v1's own files predate
// (ChoiceCardGroup, EmptyStateMedia). UPDATE when app code imports a new
// v2-only name — same contract as V2_FALLBACK_NAMES above.
const V2_ONLY_NAMES = [
  'Burst', 'ChoiceCard', 'ChoiceCardGroup', 'ContourBackdrop', 'EmptyStateMedia',
  'FunnelChart', 'GridBackdrop', 'HorizonBackdrop', 'Nodes', 'Orb', 'TopBar', 'VoidBackdrop',
]

// components/lib/* modules the HELPERS shim re-exports (both trees have them),
// and the helper names only v2's copy implements.
const V2_LIB_MODULES = ['utils', 'responsive']
const V2_ONLY_HELPERS = ['toneFromValue']

// Managed block markers in `git info/exclude` — doubles as the state that
// remembers which files a previous run injected (for stale-file cleanup).
const EXCLUDE_BEGIN = '# BEGIN inject-premium free-ds'
const EXCLUDE_END = '# END inject-premium free-ds'

function gitExcludeFile() {
  try {
    const p = execSync('git rev-parse --git-path info/exclude', { stdio: 'pipe' }).toString().trim()
    return resolve(ROOT, p)
  } catch {
    return null // no git (e.g. Vercel build container) — exclusion is moot there
  }
}

// Paths the PREVIOUS run injected, read back from the managed exclude block.
function readExcludedFreeDs() {
  const file = gitExcludeFile()
  if (!file || !existsSync(file)) return []
  try {
    const lines = readFileSync(file, 'utf8').split('\n')
    const start = lines.indexOf(EXCLUDE_BEGIN)
    const end = lines.indexOf(EXCLUDE_END)
    if (start === -1 || end === -1 || end < start) return []
    return lines.slice(start + 1, end).map((l) => l.trim()).filter((l) => l && !l.startsWith('#'))
  } catch {
    return []
  }
}

// Rewrite the managed block so `git status` never shows the injected files.
// Best-effort by design: skip silently when git is unavailable.
function syncGitExclude(paths) {
  const file = gitExcludeFile()
  if (!file) return
  try {
    let lines = []
    try { lines = readFileSync(file, 'utf8').split('\n') } catch { /* fresh file */ }
    const start = lines.indexOf(EXCLUDE_BEGIN)
    const end = lines.indexOf(EXCLUDE_END)
    if (start !== -1 && end !== -1 && end >= start) lines.splice(start, end - start + 1)
    while (lines.length && lines[lines.length - 1].trim() === '') lines.pop()
    if (paths.length > 0) lines.push('', EXCLUDE_BEGIN, ...paths, EXCLUDE_END)
    mkdirSync(dirname(file), { recursive: true })
    writeFileSync(file, lines.join('\n') + '\n')
  } catch { /* git hygiene is best-effort — never fail the build over it */ }
}

// Delete previously injected files that are no longer in the manifest (or any
// previously injected file at all on a no-vault run). The path-shape check
// means a corrupted exclude file can never delete anything outside
// design-systems/<system>/components/.
// A TRACKED file is never deleted here. info/exclude lives in the COMMON git
// dir, so the managed block is shared by every worktree of this repo: a block
// written by a run that injected over the committed v1 files (48 names, one per
// committed component) would otherwise make this pass delete those committed
// files the first time the whole-system lane runs.
// Everything git already tracks under design-systems/. Committed source is the
// repo's own; the vault only ever FILLS GAPS in it, never overwrites it.
let trackedDsFiles = new Set()
let trackedDsFilesOk = false
try {
  trackedDsFiles = new Set(
    execSync('git ls-files design-systems', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString().split('\n').map((l) => l.trim()).filter(Boolean),
  )
  trackedDsFilesOk = true
} catch { /* no git — nothing is tracked to protect */ }

function cleanupFreeDs(currentPaths) {
  const current = new Set(currentPaths)
  const tracked = trackedDsFiles
  for (const prev of readExcludedFreeDs()) {
    if (current.has(prev) || tracked.has(prev)) continue
    if (!/^design-systems\/[a-z0-9-]+\/components\/[A-Za-z][A-Za-z0-9]*\.tsx$/.test(prev)) continue
    rmSync(join(ROOT, prev), { force: true })
  }
}

// Placeholder component body — shared by the v2 shim (inline, below) and the
// degraded design-system placeholder FILES (writeFreeDsPlaceholders), so the two
// can never drift. Renders a neutral panel; spreads props onto a <div> exactly
// like the shim has always done for MetricChart/Gauge.
function placeholderFn(name) {
  return [
    `export function ${name}(props) {`,
    '  return (',
    '    <div',
    '      {...props}',
    '      style={{',
    "        background: '#141415',",
    "        border: '1px solid #3E3E3F',",
    "        color: '#9A9A9A',",
    `        fontFamily: "'JetBrains Mono', monospace",`,
    '        fontSize: 12,',
    "        letterSpacing: '0.05em',",
    '        padding: 20,',
    '        ...props.style,',
    '      }}',
    '    >',
    `      ${name} — available on the live site`,
    '    </div>',
    '  )',
    '}',
  ]
}

// Degraded/partial builds: a free-lane component was EXPECTED (manifest or the
// fallback list) but NOT injected (no vault, or a pin predating it). Write a
// sentinel-marked placeholder FILE at its design-system path so direct importers
// (e.g. the Signal Room example's `../../components/<Name>`) resolve without
// crashing next build. The sentinel makes the registry/props generators treat it
// as absent, so a placeholder is never registered or installed. On a full build
// every expected name is injected, so this writes nothing and the registry output
// is unchanged. Returns the repo-relative paths written (tracked for git-exclude +
// next-run cleanup, exactly like real injected files).
function writeFreeDsPlaceholders(system, expectedNames, injectedSet) {
  const written = []
  for (const name of expectedNames) {
    if (injectedSet.has(name)) continue
    const rel = `design-systems/${system}/components/${name}.tsx`
    // A name the repo already carries as committed source needs no placeholder:
    // the real file is right there. Writing one would replace published MIT
    // source with a stub, which is worse than the gap it was meant to fill.
    if (trackedDsFiles.has(rel)) continue
    const outFile = join(ROOT, rel)
    mkdirSync(dirname(outFile), { recursive: true })
    writeFileSync(outFile, [
      FREE_DS_PLACEHOLDER_SENTINEL,
      '// AUTO-GENERATED by scripts/inject-premium.mjs on a degraded/partial build —',
      '// the real vault component was not injected. Never committed, never registered.',
      '// @ts-nocheck',
      '',
      ...placeholderFn(name),
      '',
      `export default ${name}`,
      '',
    ].join('\n'))
    written.push(rel)
  }
  return written
}

// ALWAYS written (every run, including degraded/no-vault): the app's ONLY door
// to v2 components and tokens, so no app file names a design-systems path a
// vault-less build would not have. Injected names re-export the real source; on
// a degraded build (fork, missing PAT, older premium pin) the committed v1 tree
// stands in and the names it has no file for (V2_ONLY_NAMES) become placeholder
// panels, so the pages render instead of crashing.
//
// Shared by both the Andromeda Legacy shim (writeLegacyV2Shim, `root` always the
// committed tree) and the Andromeda Pro shim (writeProV2Shim, `root` the
// injected tree when there is one). `fromV2Tree` picks the export strategy:
// star the injected names when true, else star every committed v1 component
// file on disk and fill the v2-only gaps with placeholders.
function writeShimFile(outFile, root, injectedNames, fromV2Tree, headerLines) {
  // `export *` rather than one named export per file: a component file also
  // exports its parts (Card → CardHeader/CardTitle/…, Table → TableRow/…), and
  // the app imports those by name. Starring the file means a new subcomponent in
  // the vault needs no change here.
  const names = fromV2Tree
    ? injectedNames
    // Degraded: star every COMMITTED v1 component file that is on disk (the
    // degraded placeholders written just above are already among them), then
    // fill the v2-only gaps below.
    : readdirSync(join(ROOT, 'design-systems/andromeda/components'))
        .filter((f) => /^[A-Z][A-Za-z0-9]*\.tsx$/.test(f))
        .map((f) => f.replace(/\.tsx$/, ''))
        .sort()
  const out = [...headerLines]
  for (const name of names) out.push(`export * from '${root}/components/${name}'`)
  if (!fromV2Tree) {
    for (const name of V2_ONLY_NAMES) {
      if (names.includes(name)) continue
      out.push(...placeholderFn(name))
    }
  }
  if (fromV2Tree) {
    out.push('', `export { tokens } from '${root}/tokens'`)
  } else {
    // v1 called the two semantic colour scales orange/red; v2 renamed them
    // warning/danger. App code is written against the v2 names, so alias them
    // here rather than let a fork read undefined and throw at render — same
    // colours, same roles, nothing invented. What v1 genuinely lacks (`control`)
    // stays absent, and the one call site optional-chains it.
    out.push(
      '',
      `import { tokens as v1Tokens } from '${root}/tokens'`,
      'export const tokens = {',
      '  ...v1Tokens,',
      '  color: { ...v1Tokens.color, warning: v1Tokens.color.orange, danger: v1Tokens.color.red },',
      '}',
    )
  }
  out.push('', `export const V2_COMPONENT_NAMES = ${JSON.stringify(injectedNames)}`, '')
  writeFileSync(outFile, out.join('\n'))
}

// Andromeda LEGACY's bridge for the vault-authored free-lane components
// (freeSystemComponents.andromeda: MetricChart, Gauge, Waveform, MediaCard,
// DataTable, MusicPlayer). Root is ALWAYS the committed Legacy tree — Legacy
// never has a whole-system injection of its own — so this is a production
// contract: app/_lib/andromeda/andromeda-demos.tsx and
// app/design-systems/andromeda/system/AndromedaShowcase.tsx import the 6
// free-lane names from it on every build, injected or degraded.
function writeLegacyV2Shim(freeInjectedNames) {
  writeShimFile(V2_SHIM, '../../design-systems/andromeda', freeInjectedNames, false, [
    '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
    "// Andromeda Legacy's bridge for the vault-authored free-lane components",
    '// (freeSystemComponents.andromeda). Re-exports the injected MetricChart,',
    '// Gauge, Waveform, MediaCard, DataTable and MusicPlayer alongside the',
    '// committed Legacy component set, so andromeda-demos.tsx and',
    '// AndromedaShowcase.tsx always resolve. On a degraded build (no vault, or',
    '// an older pin) every v2-only name is a placeholder panel instead.',
    '// @ts-nocheck — re-exports untyped design-system sources.',
    '',
  ])
}

// Andromeda PRO's components + tokens shim. `fromV2Tree` is true only when the
// whole-system lane actually injected design-systems/andromeda-pro/; otherwise
// this falls back to the same committed Andromeda Legacy tree Legacy's own
// shim uses, so Pro-tree app files still compile on a fork or a pin predating
// the Pro system.
function writeProV2Shim(injectedNames, fromV2Tree) {
  const root = fromV2Tree ? '../../design-systems/andromeda-pro' : '../../design-systems/andromeda'
  writeShimFile(V2_PRO_SHIM, root, injectedNames, fromV2Tree, [
    '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
    '// Re-exports the Andromeda Pro components + tokens injected from the private',
    '// vault. On a degraded build (fork, missing PAT, older premium pin) it falls',
    '// back to the committed Andromeda Legacy tree, and any name Legacy has no',
    '// file for renders a placeholder panel, so a fork still compiles.',
    '// @ts-nocheck — re-exports untyped design-system sources.',
    '',
  ])
}

// ALWAYS written (every run) — the components/lib/* helpers app code reaches for
// (andromedaVars, mq, toneFromValue), kept OUT of the shim above on purpose:
// those helper modules import React hooks without a 'use client' directive, and
// the components shim is imported by SERVER components (the template routes read
// `tokens` from it), which makes a hook import there a build error. Only client
// modules and tests import this one. Andromeda Pro only — Legacy has no helpers
// shim of its own (nothing in the Legacy tree imports it).
function writeProHelpersShim(fromV2Tree) {
  const root = fromV2Tree ? '../../design-systems/andromeda-pro' : '../../design-systems/andromeda'
  const out = [
    '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
    '// Andromeda Pro component-lib helpers, from the injected tree when there is',
    '// one and the committed Andromeda Legacy lib otherwise. CLIENT/TEST ONLY —',
    '// these modules use React hooks, so a server component must not import this',
    '// shim.',
    '// @ts-nocheck — re-exports untyped design-system sources.',
    '',
  ]
  for (const lib of V2_LIB_MODULES) out.push(`export * from '${root}/components/lib/${lib}'`)
  // Named palette snapshots (the dev-only theme dock lists them). v2-tree only:
  // the committed v1 lib has no such folder, and a missing module is a hard
  // build error where a missing named export is merely inert.
  out.push(
    fromV2Tree
      ? `export * from '${root}/components/lib/palettes'`
      : 'export const ANDROMEDA_PALETTES = {}',
  )
  if (!fromV2Tree) {
    // Helpers v1's lib has no implementation for. An explicit export shadows a
    // star one, so this only ever wins while the real thing is genuinely absent.
    // Inert on purpose: nothing RENDERS from these, and the one test that reads
    // toneFromValue skips itself on a degraded build (V2_COMPONENT_NAMES empty).
    const v1Utils = readFileSync(join(ROOT, 'design-systems/andromeda/components/lib/utils.ts'), 'utf8')
    for (const name of V2_ONLY_HELPERS) {
      if (v1Utils.includes(`export function ${name}`)) continue
      out.push(`export const ${name} = (...args) => null`)
    }
  }
  out.push('')
  writeFileSync(V2_PRO_HELPERS_SHIM, out.join('\n'))
}

// ── Vault-authored template compositions ────────────────────────────────────
// Exported name → example folder under design-systems/<tree>/examples/. The
// Andromeda Pro template routes (app/design-systems/andromeda-pro/templates/
// <slug>/page.tsx) import their composition from the generated shim rather than
// the tree, so the module resolves on EVERY build: the injected Pro example when
// there is one, the committed Legacy example when there isn't (forks keep their
// four templates), and a placeholder panel for a Pro-only composition like
// sign-in. Same committed-fallback contract as V2_FALLBACK_NAMES — UPDATE when a
// template route lands.
const V2_EXAMPLE_EXPORTS = {
  MissionControl: 'mission-control',
  ResourcePlanning: 'resource-planning',
  ServiceOrder: 'service-order',
  SignIn: 'sign-in',
  SignalRoom: 'signal-room',
}

// ALWAYS written (every run, including degraded/no-vault) — see above. Andromeda
// Pro only — nothing in the Legacy tree imports an examples shim.
function writeProExamplesShim() {
  const out = [
    '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
    '// Template compositions for the Andromeda Pro template routes: the injected',
    '// Pro example, else the committed Andromeda Legacy one, else a placeholder',
    '// panel.',
    '// @ts-nocheck — re-exports untyped design-system sources.',
    '',
  ]
  for (const [name, slug] of Object.entries(V2_EXAMPLE_EXPORTS)) {
    const pro = `design-systems/andromeda-pro/examples/${slug}`
    const legacy = `design-systems/andromeda/examples/${slug}`
    const from = existsSync(join(ROOT, pro, 'index.tsx'))
      ? pro
      : existsSync(join(ROOT, legacy, 'index.tsx'))
        ? legacy
        : null
    if (from) out.push(`export { default as ${name} } from '../../${from}'`)
    else out.push(...placeholderFn(name))
  }
  out.push('')
  writeFileSync(V2_PRO_EXAMPLES_SHIM, out.join('\n'))
}

// ── Whole-system v2 trees (manifest key `systems`) ──────────────────────────
// A system listed in `systems` ships as a WHOLE TREE: the vault's
// design-systems/<slug>/ is copied to the gitignored design-systems/<slug>-v2/,
// CODE ONLY. Brain material (rules, foundations, skills, tools, inventories) is
// premium and must never land in the working tree — it ships gated as JSON via
// the brains lane below. Anything not listed here is copied, so a new code file
// in the vault needs no change on this side.
const BRAIN_FILES = new Set(['README.md', 'INVENTORY.md', 'rules.md'])
const BRAIN_DIRS = new Set(['_skills', '_tools', 'foundations'])
const isBrainFile = (name) => BRAIN_FILES.has(name) || /\.rules\.md$|\.selfcheck\.mjs$/.test(name)

// Recursive copy with the brain filter + the same marker strip the standalone
// lane uses (the served/rendered code must be clean). Returns the file count.
function copySystemTree(srcDir, outDir) {
  let copied = 0
  for (const entry of readdirSync(srcDir, { withFileTypes: true })) {
    const from = join(srcDir, entry.name)
    if (entry.isDirectory()) {
      if (BRAIN_DIRS.has(entry.name)) continue
      copied += copySystemTree(from, join(outDir, entry.name))
      continue
    }
    if (!entry.isFile() || isBrainFile(entry.name)) continue
    mkdirSync(outDir, { recursive: true })
    writeFileSync(join(outDir, entry.name), stripMarkerBlock(readFileSync(from, 'utf8')))
    copied++
  }
  return copied
}

// ── Brains (manifest key `brains`) ──────────────────────────────────────────
// The design-system brain (rules.md + foundations/*.md + components/*.rules.md)
// is PREMIUM content. It never touches the public working tree as .md — it is
// bundled into registry-data/_<slug>-brain.json, which the gated brain page
// reads server-side. The leading underscore matters: the /r/[file] route's
// filename regex rejects underscores (same convention as _manifest.json /
// _premium.json), so the brain JSON is structurally unservable — no gate
// change needed, no leak possible via /r.

// Fallback teaser for the brain paywall — NAMES AND COUNTS ONLY, never content.
// The paywall imports the generated teaser module on every build, so a
// degraded build (fork, missing PAT, older premium pin) still renders real
// structure. UPDATE when the brain grows (mirror of the vault's
// design-systems/andromeda/ brain folder), same contract as V2_FALLBACK_NAMES.
const BRAIN_TEASER_FALLBACK = {
  totalFiles: 56,
  sections: [
    {
      id: 'index',
      label: 'Index',
      files: ['rules', 'INVENTORY'],
    },
    {
      id: 'foundations',
      label: 'Foundations',
      files: [
        'anti-patterns', 'build-workflow', 'charts', 'color-philosophy',
        'composition-recipes', 'defaults', 'interaction-states', 'layout',
        'motion', 'responsive', 'spacing', 'voice-and-copy',
      ],
    },
    {
      id: 'component-rules',
      label: 'Component Rules',
      files: [
        'Alert', 'Avatar', 'Badge', 'Button', 'Card', 'Checkbox',
        'CornerMarkers', 'DataTable', 'DateRangePicker', 'Drawer',
        'EmptyState', 'Gauge', 'HeatGrid', 'IconButton', 'Input', 'MediaCard',
        'MetricChart', 'MusicPlayer', 'NavItem', 'PanelHeader', 'PanelMenu',
        'Planet', 'ProgressBar', 'RadarChart', 'Radio', 'SearchField',
        'SegmentedControl', 'Slider', 'Spinner', 'StatTile', 'Table', 'Tag',
        'Textarea', 'Toggle', 'Tooltip', 'TopBar', 'TrendChart', 'UserCard', 'UserMenu',
        'Waveform',
      ],
    },
    {
      id: 'skills',
      label: 'Skills',
      files: ['building-with-andromeda', 'reviewing-against-andromeda'],
    },
    {
      id: 'tools',
      label: 'Tools',
      files: ['verify-andromeda'],
    },
  ],
}

// Every bundled file TYPE must have a section to appear in. Without this map a
// new type is silently counted in totalFiles and then rendered nowhere, which
// is exactly how the brain came to advertise 56 files while both reader pages
// let you browse 53: `index`, `inventory` and `tool` each had a type and no
// home. Order here is the order sections render.
const TEASER_SECTIONS = [
  { id: 'index', label: 'Index', types: ['index', 'inventory'] },
  { id: 'foundations', label: 'Foundations', types: ['foundation'] },
  { id: 'component-rules', label: 'Component Rules', types: ['component-rule'] },
  { id: 'skills', label: 'Skills', types: ['skill'] },
  { id: 'tools', label: 'Tools', types: ['tool'] },
]

/**
 * Group the bundled files into reader sections, refusing to ship a brain whose
 * file types do not all have one.
 *
 * Three guards, deliberately different in what they tolerate:
 *   - an unsectioned TYPE is fatal. It is the bug this exists to stop, and it
 *     can never fire on ordinary growth, since a 40th component rule is still
 *     type `component-rule`.
 *   - the fallback missing a SECTION ID is fatal, because a degraded build
 *     would then advertise a shape the brain no longer has.
 *   - the fallback's per-section COUNTS lagging is a note, not a failure. They
 *     change every time the brain grows, so failing there would cry wolf on
 *     every build and train everyone to ignore the guard that matters.
 */
function buildTeaserSections(files, slug) {
  const homeless = [...new Set(files.map((f) => f.type))].filter(
    (t) => !TEASER_SECTIONS.some((s) => s.types.includes(t)),
  )
  if (homeless.length) {
    console.error(
      `[inject-premium] brain "${slug}": file type(s) ${homeless.join(', ')} have no teaser section. ` +
        'Add them to TEASER_SECTIONS — otherwise the reader counts these files and never shows them.',
    )
    process.exit(1)
  }

  const nameOf = (f) =>
    f.type === 'skill'
      // _skills/<name>/SKILL.md — every basename is "SKILL", so use the folder.
      ? f.path.split('/').at(-2)
      : f.path.split('/').at(-1).replace(/\.rules\.md$/, '').replace(/\.(md|mjs)$/, '')

  const sections = TEASER_SECTIONS.map((s) => ({
    id: s.id,
    label: s.label,
    files: files.filter((f) => s.types.includes(f.type)).map(nameOf),
  })).filter((s) => s.files.length)

  const missing = sections
    .map((s) => s.id)
    .filter((id) => !BRAIN_TEASER_FALLBACK.sections.some((f) => f.id === id))
  if (missing.length) {
    console.error(
      `[inject-premium] BRAIN_TEASER_FALLBACK is missing section(s): ${missing.join(', ')}. ` +
        'Degraded builds would advertise a shape the brain no longer has — update the fallback above.',
    )
    process.exit(1)
  }

  const drifted = sections
    .map((s) => [s, BRAIN_TEASER_FALLBACK.sections.find((x) => x.id === s.id)])
    .filter(([s, f]) => f && f.files.length !== s.files.length)
  if (drifted.length) {
    log(
      `note: BRAIN_TEASER_FALLBACK counts lag the brain (${drifted
        .map(([s, f]) => `${s.id} ${f.files.length}->${s.files.length}`)
        .join(', ')}) — cosmetic, degraded builds only.`,
    )
  }

  return sections
}

// ALWAYS written (every run, including degraded/no-vault): the brain paywall
// statically imports BRAIN_TEASER, so the module must exist on every build.
// Structure only (file names + counts) — never brain content. One call per
// slug (Legacy → BRAIN_TEASER_MODULE, Pro → BRAIN_TEASER_PRO_MODULE); both fall
// back to the same BRAIN_TEASER_FALLBACK snapshot when their slug wasn't bundled.
function writeBrainTeaser(outFile, teaser) {
  const data = teaser ?? BRAIN_TEASER_FALLBACK
  writeFileSync(
    outFile,
    [
      '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
      '// Structure-only teaser for the Andromeda Brain paywall: section labels, file',
      '// NAMES and counts — never brain content. Derived from the real vault brain',
      '// when reachable; a committed fallback snapshot on degraded builds.',
      '// @ts-nocheck',
      `export const BRAIN_TEASER = ${JSON.stringify(data, null, 2)} as const`,
      '',
    ].join('\n'),
  )
}

// Collect a brain's files from the vault source. Returns { files, teaser } or
// exits loudly — a manifest-listed brain with a missing/empty source folder is
// a broken publish, never a silent skip (when the vault IS reachable).
function collectBrain(source, slug) {
  const sysDir = join(source, 'design-systems', slug)
  const rulesPath = join(sysDir, 'rules.md')
  if (!existsSync(rulesPath)) {
    console.error(`[inject-premium] manifest brains lists "${slug}" but design-systems/${slug}/rules.md is missing from the premium source`)
    process.exit(1)
  }
  const listMd = (dir, suffix) => {
    try {
      return readdirSync(join(sysDir, dir)).filter((f) => f.endsWith(suffix)).sort()
    } catch {
      return []
    }
  }
  const foundations = listMd('foundations', '.md')
  const componentRules = listMd('components', '.rules.md')
  // Runnable checks the CONSUMER executes against their own code (e.g.
  // verify-andromeda.mjs, which names the replacement token for every colour
  // finding and gates 'done' on the mechanical checks).
  // The rules say what is right; these are what make it verifiable, so they
  // ship with the rules rather than staying maintainer-side.
  const tools = listMd('_tools', '.mjs')
  // Skills are folders under _skills/, each with a SKILL.md (Claude Code shape).
  const skills = (() => {
    try {
      return readdirSync(join(sysDir, '_skills'), { withFileTypes: true })
        .filter((d) => d.isDirectory() && existsSync(join(sysDir, '_skills', d.name, 'SKILL.md')))
        .map((d) => d.name)
        .sort()
    } catch {
      return []
    }
  })()
  if (foundations.length === 0 && componentRules.length === 0) {
    console.error(`[inject-premium] brain "${slug}" has no foundations/*.md and no components/*.rules.md — refusing to ship an empty brain`)
    process.exit(1)
  }
  const read = (rel) => readFileSync(join(sysDir, rel), 'utf8')
  // INVENTORY.md is generated vault-side (scripts/generate-inventory.mjs): every
  // component with its purpose, props, variants and forbids in ONE file. It is
  // how an agent answers "do we already have this?" without opening 39 rules
  // files, so it ships when present. Optional — a system may not have one yet.
  const hasInventory = existsSync(join(sysDir, 'INVENTORY.md'))
  const files = [
    { path: `design-systems/${slug}/rules.md`, content: read('rules.md'), type: 'index' },
    ...(hasInventory
      ? [{ path: `design-systems/${slug}/INVENTORY.md`, content: read('INVENTORY.md'), type: 'inventory' }]
      : []),
    ...foundations.map((f) => ({
      path: `design-systems/${slug}/foundations/${f}`,
      content: read(join('foundations', f)),
      type: 'foundation',
    })),
    ...componentRules.map((f) => ({
      path: `design-systems/${slug}/components/${f}`,
      content: read(join('components', f)),
      type: 'component-rule',
    })),
    ...skills.map((name) => ({
      path: `design-systems/${slug}/_skills/${name}/SKILL.md`,
      content: read(join('_skills', name, 'SKILL.md')),
      type: 'skill',
    })),
    ...tools.map((f) => ({
      path: `design-systems/${slug}/_tools/${f}`,
      content: read(join('_tools', f)),
      type: 'tool',
    })),
  ]
  // Sections are derived from the bundled files themselves, never listed by
  // hand here, so totalFiles and the sections can never disagree again.
  const teaser = {
    totalFiles: files.length,
    sections: buildTeaserSections(files, slug),
  }
  return { files, teaser }
}

// Always start from a clean slate so a removed slug actually disappears. Recreate
// the (possibly empty) target dir so the Tailwind `@source` for it always resolves,
// even on free-only builds.
rmSync(TARGET, { recursive: true, force: true })
rmSync(SHIM, { force: true })
rmSync(V2_SHIM, { force: true })
rmSync(V2_PRO_SHIM, { force: true })
rmSync(V2_PRO_EXAMPLES_SHIM, { force: true })
rmSync(V2_PRO_HELPERS_SHIM, { force: true })
rmSync(BRAIN_TEASER_MODULE, { force: true })
rmSync(BRAIN_TEASER_PRO_MODULE, { force: true })
rmSync(PREMIUM_JSON, { force: true })
rmSync(BUILD_INFO, { force: true })
// Stale brain files from a previous run: the underscore-prefixed page bundle
// AND the servable <slug>-brain.json CLI item. Removed up front so a degraded
// run leaves NO brain content behind (bundled or servable). NB: this would
// also delete a hypothetical free standalone whose slug ends in `-brain` —
// harmless (generate-registry re-emits it later in the same chain), but avoid
// naming standalones that way.
try {
  for (const f of readdirSync(REGISTRY_DATA)) {
    if (/^_?[a-z0-9-]+-brain\.json$/.test(f)) rmSync(join(REGISTRY_DATA, f), { force: true })
  }
} catch { /* registry-data not created yet */ }
// Injected-only whole-system trees (DESIGN_SYSTEMS entries with skipIfMissing,
// e.g. design-systems/andromeda-pro/) — cleared up front so a removed slug, a
// renamed component, or a degraded run leaves nothing behind. Guarded by
// trackedDsFiles rather than the manifest (not read yet): a rootDir that
// genuinely carries committed source is never touched, even if it were
// mistakenly marked skipIfMissing. When git ls-files failed (trackedDsFilesOk
// false, e.g. no git in a Vercel build container) this must SKIP rather than
// risk deleting real source it has no way to verify is absent.
if (trackedDsFilesOk) {
  for (const ds of DESIGN_SYSTEMS) {
    if (!ds.skipIfMissing) continue
    const prefix = ds.rootDir + '/'
    const hasTrackedSource = [...trackedDsFiles].some((f) => f.startsWith(prefix))
    if (!hasTrackedSource) rmSync(join(ROOT, ds.rootDir), { recursive: true, force: true })
  }
} else {
  log('warning: git ls-files failed — skipping injected-only design-system cleanup (would otherwise risk deleting committed source it cannot verify is absent).')
}
// One-time leftovers from the pre-split layout (design-systems/<slug>-v2/ and
// the old shared Pro shim names) — force-removed unconditionally so a stale
// worktree self-heals even though nothing writes these paths anymore.
rmSync(join(ROOT, 'design-systems/andromeda-v2'), { recursive: true, force: true })
rmSync(join(ROOT, 'app/lib/andromeda-v2-examples.generated.tsx'), { force: true })
rmSync(join(ROOT, 'app/lib/andromeda-v2-helpers.generated.tsx'), { force: true })
mkdirSync(TARGET, { recursive: true })

// ── 1. Resolve the source ──────────────────────────────────────────────────
let source = process.env.PREMIUM_LOCAL_PATH || ''
let tmpClone = ''
if (!source && process.env.GITHUB_PAT_PREMIUM) {
  tmpClone = '/tmp/aicanvas-premium-inject'
  rmSync(tmpClone, { recursive: true, force: true })
  const remote = `https://x-access-token:${process.env.GITHUB_PAT_PREMIUM}@github.com/aicanvas-me/aicanvas-premium.git`
  try {
    execSync(`git clone --depth 1 ${remote} "${tmpClone}"`, { stdio: 'pipe' })
  } catch (e) {
    // 3-state PAT: set-but-clone-failed = auth/expiry → FAIL LOUD (never a silent
    // free-only ship to paying customers).
    console.error(
      '\n🚫 [inject-premium] PREMIUM PAT REJECTED — clone failed. Rotate ' +
        'GITHUB_PAT_PREMIUM in Vercel (likely the 90-day expiry).\n' +
        (e.stderr ? e.stderr.toString() : e.message),
    )
    process.exit(1)
  }
  // Pin: build the EXACT committed sha (premium.lock.json), not whatever `main`
  // happens to be right now. Fetch-by-sha works even if the pin isn't the tip, and
  // only succeeds for commits actually pushed to the remote — so an unpushed WIP sha
  // can never build. A missing/unreachable pin FAILS LOUD rather than shipping the
  // wrong premium.
  if (pinnedSha) {
    try {
      execSync(`git -C "${tmpClone}" fetch --depth 1 ${remote} ${pinnedSha}`, { stdio: 'pipe' })
      execSync(`git -C "${tmpClone}" checkout --quiet ${pinnedSha}`, { stdio: 'pipe' })
    } catch (e) {
      console.error(
        '\n🚫 [inject-premium] PINNED PREMIUM COMMIT NOT REACHABLE: ' + pinnedSha + '\n' +
          '   premium.lock.json points at a commit that is not on the aicanvas-premium ' +
          'remote.\n   Fix the pin (usually via `npm run publish-premium`), do not ship.\n' +
          (e.stderr ? e.stderr.toString() : e.message),
      )
      process.exit(1)
    }
    const head = execSync(`git -C "${tmpClone}" rev-parse HEAD`).toString().trim()
    if (head !== pinnedSha) {
      console.error('\n🚫 [inject-premium] pin checkout mismatch: wanted ' + pinnedSha + ' got ' + head)
      process.exit(1)
    }
  } else {
    console.error(
      '\n🚫 [inject-premium] no premium.lock.json pin found for a PAT build. Refusing to ' +
        'build against floating `main`. Commit premium.lock.json (via publish-premium).',
    )
    process.exit(1)
  }
  source = tmpClone
}

if (!source) {
  writeStubShim()
  writeBuildInfo(null)
  // Free v2 DS components: no vault reachable — remove any previously injected
  // copies (mirrors the standalone clean-slate above), empty the exclude block,
  // and write the placeholder shim so the showcase still compiles + renders.
  const freePlaceholders = writeFreeDsPlaceholders('andromeda', V2_FALLBACK_NAMES, new Set())
  cleanupFreeDs(freePlaceholders)
  syncGitExclude(freePlaceholders)
  writeLegacyV2Shim([])
  writeProV2Shim([], false)
  writeProHelpersShim(false)
  writeProExamplesShim()
  // Brain: no bundle (the page fail-closes to the paywall), but the paywall's
  // teaser modules must still exist — write both from the committed fallback.
  writeBrainTeaser(BRAIN_TEASER_MODULE, null)
  writeBrainTeaser(BRAIN_TEASER_PRO_MODULE, null)
  log('no PREMIUM_LOCAL_PATH and no GITHUB_PAT_PREMIUM — free-only build (skip).')
  process.exit(0)
}

// The exact commit actually injected: the pinned sha on a PAT build, or your local
// checkout's HEAD in dev. Stamped into build-info so /api/premium/health can prove it.
let builtSha = null
try {
  builtSha = execSync(`git -C "${source}" rev-parse HEAD`).toString().trim()
} catch {
  builtSha = null
}
if (process.env.PREMIUM_LOCAL_PATH && pinnedSha && builtSha && builtSha !== pinnedSha) {
  log(`note: dev checkout ${builtSha.slice(0, 7)} differs from the production pin ${pinnedSha.slice(0, 7)} (expected while iterating).`)
}

// ── 2. Manifest ────────────────────────────────────────────────────────────
let manifest
try {
  manifest = JSON.parse(readFileSync(join(source, 'premium-manifest.json'), 'utf8'))
} catch (e) {
  console.error('[inject-premium] cannot read premium-manifest.json at ' + source + ': ' + e.message)
  process.exit(1)
}
// NB: no early exit on 0 standalones — the free-DS phase below must still run.
// With an empty list the copy loop + bijection are no-ops and the registration
// shim comes out empty (equivalent to the stub).
// PREMIUM_SKIP_SLUGS (dev only): comma-separated standalone slugs to leave out
// of this run — for pointing PREMIUM_LOCAL_PATH at a vault branch carrying
// another task's WIP slug this checkout has no registry rows for. Filtered
// before any lane so the folder/manifest bijection stays consistent.
const skipSlugs = new Set(
  (process.env.PREMIUM_SKIP_SLUGS ?? '').split(',').map((s) => s.trim()).filter(Boolean),
)
if (skipSlugs.size > 0 && Array.isArray(manifest.standalones)) {
  manifest.standalones = manifest.standalones.filter((s) => !skipSlugs.has(s))
  log(`PREMIUM_SKIP_SLUGS: leaving out ${[...skipSlugs].join(', ')}`)
}
const standalones = Array.isArray(manifest.standalones) ? [...manifest.standalones] : []

mkdirSync(TARGET, { recursive: true })
mkdirSync(join(ROOT, 'registry-data'), { recursive: true })

// ── 3. Copy each component, stripping the marker ───────────────────────────
const injected = []
for (const slug of standalones) {
  if (!/^[a-z0-9-]+$/.test(slug)) {
    console.error('[inject-premium] invalid slug in manifest: ' + JSON.stringify(slug))
    process.exit(1)
  }
  const srcDir = join(source, 'components-workspace', slug)
  const idx = join(srcDir, 'index.tsx')
  if (!existsSync(idx)) {
    console.error('[inject-premium] manifest slug "' + slug + '" has no components-workspace/' + slug + '/index.tsx')
    process.exit(1)
  }
  const metaPath = join(srcDir, 'meta.json')
  if (!existsSync(metaPath)) {
    console.error('[inject-premium] "' + slug + '" is missing meta.json')
    process.exit(1)
  }
  const meta = JSON.parse(readFileSync(metaPath, 'utf8'))
  if (!meta.name || !meta.description) {
    console.error('[inject-premium] "' + slug + '" meta.json must have name + description')
    process.exit(1)
  }

  const outDir = join(TARGET, slug)
  mkdirSync(outDir, { recursive: true })
  const stripped = stripMarkerBlock(readFileSync(idx, 'utf8'))
  writeFileSync(join(outDir, 'index.tsx'), stripped)
  cpSync(metaPath, join(outDir, 'meta.json'))

  const promptsPath = join(srcDir, 'prompts.ts')
  const hasPrompts = existsSync(promptsPath)
  if (hasPrompts) {
    const strippedPrompts = stripMarkerBlock(readFileSync(promptsPath, 'utf8'))
    writeFileSync(join(outDir, 'prompts.ts'), strippedPrompts)
  }

  injected.push({ slug, meta, hasPrompts })
}

// ── 4. Bijection: manifest ⇄ injected folders ──────────────────────────────
const folderSlugs = readdirSync(TARGET)
  .filter((d) => { try { return statSync(join(TARGET, d, 'index.tsx')).isFile() } catch { return false } })
  .sort()
const manifestSlugs = [...standalones].sort()
if (JSON.stringify(folderSlugs) !== JSON.stringify(manifestSlugs)) {
  console.error('[inject-premium] manifest/folder mismatch:\n  manifest: ' + manifestSlugs.join(', ') + '\n  folders:  ' + folderSlugs.join(', '))
  process.exit(1)
}

// ── 4a. Whole-system trees (manifest key `systems`) ─────────────────────────
// The vault's design-systems/<slug>/ copied wholesale (code only) to that
// slug's own DESIGN_SYSTEMS entry (an injected-only system, rootDir e.g.
// design-systems/andromeda-pro/). Absent/empty key → no-op, so a production
// pin on an older vault sha still builds green on the lane below.
const v2Systems = Array.isArray(manifest.systems) ? [...manifest.systems] : []
const v2Components = {} // system → [ComponentName], from what actually landed
for (const system of v2Systems) {
  if (!/^[a-z0-9-]+$/.test(system)) {
    console.error('[inject-premium] invalid system slug in systems: ' + JSON.stringify(system))
    process.exit(1)
  }
  const ds = DESIGN_SYSTEMS.find((d) => d.slug === system)
  if (!ds || !ds.skipIfMissing) {
    console.error(
      `[inject-premium] manifest systems lists "${system}" but the site declares no ` +
        `injected-only design system "${system}" (scripts/lib/design-systems.config.mjs ` +
        'needs a DESIGN_SYSTEMS entry for it with skipIfMissing: true)',
    )
    process.exit(1)
  }
  if ([...trackedDsFiles].some((f) => f.startsWith(ds.rootDir + '/'))) {
    console.error(
      `[inject-premium] refusing to inject whole-system "${system}" over committed source ` +
        `under ${ds.rootDir}/ — an injected-only system must never share a rootDir with ` +
        'tracked files',
    )
    process.exit(1)
  }
  const srcDir = join(source, 'design-systems', system)
  // Mirror of the standalone/free-DS checks: a manifest-listed system missing
  // from the vault source is a broken publish — fail loud, never ship half a
  // design system.
  if (!existsSync(join(srcDir, 'tokens.ts'))) {
    console.error(`[inject-premium] manifest systems lists "${system}" but design-systems/${system}/tokens.ts is missing from the premium source`)
    process.exit(1)
  }
  const outDir = join(ROOT, ds.rootDir)
  const fileCount = copySystemTree(srcDir, outDir)
  v2Components[system] = readdirSync(join(outDir, 'components'))
    .filter((f) => /^[A-Z][A-Za-z0-9]*\.tsx$/.test(f))
    .map((f) => f.replace(/\.tsx$/, ''))
    .sort()
  log(
    `injected system "${system}": ${fileCount} file(s) → ${ds.rootDir}/ ` +
      `(${v2Components[system].length} components)`,
  )
}

// ── 4b. Free design-system components ───────────────────────────────────────
// These land in Andromeda LEGACY's committed tree, so they must be written
// against Legacy's tokens and lib. In production that is automatic: the pin is
// one vault sha and its versions are the Legacy-shaped ones. In DEV, when
// PREMIUM_LOCAL_PATH points at the Andromeda Pro branch, that branch's copies
// are written against PRO's lib instead (Waveform imports useResolvedVars,
// which Legacy's utils does not export) and every page rendering them 500s.
// PREMIUM_FREE_LANE_PATH lets dev read this lane from vault main while the
// whole-system lane above still reads the Pro branch. Unset in production, so
// the pinned source is used exactly as before.
const freeSource = process.env.PREMIUM_FREE_LANE_PATH
  ? resolve(process.env.PREMIUM_FREE_LANE_PATH)
  : source
if (freeSource !== source) {
  log(`free-lane source override: ${freeSource}`)
}
// manifest.freeSystemComponents: { <system>: [<ComponentName>, ...] }.
// Copied into the public design-systems tree (marker-stripped, like the
// standalones) so relative imports ('../tokens', './lib/utils', './Badge')
// resolve against the committed v1 files. Absent/empty key → no-op, so a
// production pin on an older vault sha (pre-dating the key) still builds green.
const freeMap =
  manifest.freeSystemComponents && typeof manifest.freeSystemComponents === 'object'
    ? manifest.freeSystemComponents
    : {}
const freeInjected = {} // system → [ComponentName]
const freePaths = []    // repo-relative injected file paths
for (const [system, names] of Object.entries(freeMap)) {
  if (!/^[a-z0-9-]+$/.test(system)) {
    console.error('[inject-premium] invalid system slug in freeSystemComponents: ' + JSON.stringify(system))
    process.exit(1)
  }
  // NOT superseded by the whole-system lane. Andromeda Legacy and Andromeda Pro
  // are two separate systems now: the whole-system lane fills Pro's tree under
  // design-systems/<system>-v2/, while this lane puts the free-lane components
  // into LEGACY's committed tree, which is where its pages and registry read
  // them from. Skipping it here left Legacy with degraded placeholders.
  for (const name of Array.isArray(names) ? names : []) {
    if (!/^[A-Za-z][A-Za-z0-9]*$/.test(name)) {
      console.error('[inject-premium] invalid component name in freeSystemComponents: ' + JSON.stringify(name))
      process.exit(1)
    }
    const rel = `design-systems/${system}/components/${name}.tsx`
    // The manifest's free lane still lists every Pro component, but a name the
    // repo already carries as committed MIT source is Legacy's own: writing the
    // vault's version over it would silently replace 33 published MIT files
    // with Pro source. Committed always wins; the vault fills the gaps only.
    if (trackedDsFiles.has(rel)) continue
    const src = join(freeSource, rel)
    // Mirror of the standalone bijection check: a manifest-listed file missing
    // from the vault source is a broken publish — fail loud, never ship a
    // showcase that imports a component that does not exist.
    if (!existsSync(src)) {
      // With a deliberate free-lane override the source is a DIFFERENT vault sha
      // than the manifest came from, so a name it does not carry is expected:
      // the manifest lists every Pro component, and vault main only holds the
      // few that Andromeda Legacy actually ships. Without an override the source
      // and the manifest are one sha, and a gap is a broken publish: fail loud.
      if (freeSource !== source) continue
      console.error(`[inject-premium] freeSystemComponents lists "${system}/${name}" but ${rel} is missing from the premium source`)
      process.exit(1)
    }
    const outFile = join(ROOT, rel)
    mkdirSync(dirname(outFile), { recursive: true })
    const strippedSrc = stripMarkerBlock(readFileSync(src, 'utf8'))
    writeFileSync(outFile, strippedSrc)
    ;(freeInjected[system] ??= []).push(name)
    freePaths.push(rel)
  }
}
// Fill any expected-but-not-injected gap with sentinel placeholders so direct
// importers resolve even on a partial pin. On a full build (all names injected)
// this writes nothing, so freePaths and the registry output are unchanged.
// On the whole-system lane the manifest list is NOT the expected set here —
// those names live under Andromeda Pro's own rootDir (design-systems/
// andromeda-pro/) now, and most of them also name a COMMITTED v1 file that a
// placeholder would overwrite. Only V2_FALLBACK_NAMES still need a file in the
// v1 tree: they are the names the committed v1 examples (signal-room,
// service-order, …) import but that were never tracked.
const andromedaInjected = new Set(freeInjected['andromeda'] ?? [])
const andromedaExpected = [...new Set([
  ...(Array.isArray(freeMap['andromeda']) ? freeMap['andromeda'] : []),
  ...V2_FALLBACK_NAMES,
])]
const freePlaceholders = writeFreeDsPlaceholders('andromeda', andromedaExpected, andromedaInjected)
const allFreePaths = [...freePaths, ...freePlaceholders]
cleanupFreeDs(allFreePaths)  // previously injected, no longer in the manifest
syncGitExclude(allFreePaths) // keep `git status` clean (skips silently without git)
// Andromeda Legacy's own shim: always the degraded/committed-tree branch (Legacy
// never has a whole-system injection), fed by the free-lane names actually
// injected above.
writeLegacyV2Shim(freeInjected['andromeda'] ?? [])
// Andromeda Pro's shims: the whole-system tree when "andromeda-pro" was
// injected (v2Components keyed by slug), else the same degraded fallback as
// Legacy so Pro-tree app files still compile.
writeProV2Shim(
  v2Components['andromeda-pro'] ?? freeInjected['andromeda-pro'] ?? [],
  Boolean(v2Components['andromeda-pro']),
)
writeProHelpersShim(Boolean(v2Components['andromeda-pro']))
writeProExamplesShim()
if (freePlaceholders.length > 0) {
  log(`wrote ${freePlaceholders.length} degraded placeholder(s) for expected-but-not-injected free component(s): ` +
    freePlaceholders.map((p) => p.split('/').pop().replace('.tsx', '')).join(', '))
}
if (freePaths.length > 0) {
  log(
    `injected ${freePaths.length} free design-system component(s): ` +
      Object.entries(freeInjected).map(([s, ns]) => ns.map((n) => `${s}/${n}`).join(', ')).join(', '),
  )
}

// ── 4c. Brains ──────────────────────────────────────────────────────────────
// manifest.brains: [<system slug>]. Bundle each brain's .md files (index +
// foundations + component rules) into registry-data/_<slug>-brain.json for the
// gated brain page, and write the paywall teaser module (names/counts only).
// Absent/empty key → no bundle, fallback teaser (older pins stay green).
const brains = Array.isArray(manifest.brains) ? [...manifest.brains] : []
// ── Design-system remix prompts ─────────────────────────────────────────────
// One hand-written markdown brief per Andromeda Pro component, authored in the
// vault at design-systems/<system>/prompts/<Name>.md. This is PAID content: it
// lands in an underscore-prefixed file, which the /r route's filename regex
// refuses to serve, and reaches a page only through the server-side gate in
// app/design-systems/andromeda-pro/[component]/page.tsx.
//
// Absent-tolerant on purpose: the prompts are being authored on their own vault
// branch, so a source without them writes an empty bundle and every page simply
// renders no Remix panel, exactly as it did before this lane existed.
for (const system of v2Systems) {
  const promptDir = join(source, 'design-systems', system, 'prompts')
  const prompts = {}
  if (existsSync(promptDir)) {
    for (const f of readdirSync(promptDir).sort()) {
      if (!/^[A-Z][A-Za-z0-9]*\.md$/.test(f)) continue
      prompts[f.replace(/\.md$/, '')] = stripMarkerBlock(readFileSync(join(promptDir, f), 'utf8'))
    }
  }
  writeFileSync(
    join(REGISTRY_DATA, `_${system}-prompts.json`),
    JSON.stringify({ generatedAt: builtSha ?? 'local', prompts }, null, 2) + '\n',
  )
  const n = Object.keys(prompts).length
  log(n > 0
    ? `bundled ${n} remix prompt(s) for "${system}" → registry-data/_${system}-prompts.json`
    : `no remix prompts in the source for "${system}" — empty bundle, panels stay hidden`)
}
// A design system declared in the site config but NOT in this run's manifest
// systems (e.g. Legacy, which never gets a prompts bundle; or Pro on a
// degraded/pre-split pin) must not keep a stale bundle from an earlier run.
for (const ds of DESIGN_SYSTEMS) {
  if (v2Systems.includes(ds.slug)) continue
  rmSync(join(REGISTRY_DATA, `_${ds.slug}-prompts.json`), { force: true })
}

const brainSlugs = []
const brainTeasers = {} // slug → teaser, for the per-slug paywall teaser modules below
for (const slug of brains) {
  if (!/^[a-z0-9-]+$/.test(slug)) {
    console.error('[inject-premium] invalid brain slug in manifest: ' + JSON.stringify(slug))
    process.exit(1)
  }
  const { files, teaser } = collectBrain(source, slug)
  writeFileSync(
    join(REGISTRY_DATA, `_${slug}-brain.json`),
    JSON.stringify({ generatedAt: builtSha ?? 'local', files }, null, 2) + '\n',
  )
  // Servable CLI item: <slug>-brain.json (NO underscore, so /r CAN serve it —
  // the gate classifies it 'brain' and requires premium entitlement mode-
  // independently, exactly like premium-standalone; non-premium gets a stub).
  // Same files as the page bundle, in shadcn registry-item shape with explicit
  // `~/` targets so `npx shadcn add` lands them at design-systems/<slug>/... in
  // the consumer's project. Re-running the command refreshes the rules in place.
  const title = slug.charAt(0).toUpperCase() + slug.slice(1)
  writeFileSync(
    join(REGISTRY_DATA, `${slug}-brain.json`),
    JSON.stringify(
      {
        $schema: 'https://ui.shadcn.com/schema/registry-item.json',
        name: `${slug}-brain`,
        type: 'registry:item',
        title: `${title} Brain`,
        description:
          // Names the kinds the corpus actually ships. It used to say "every
          // rule, foundation, and skill", which counts three while the bundle
          // carries five: the index and the tools were invisible here too.
          `The ${title} design-system brain: every foundation, component rule, skill and tool as ` +
          `markdown your AI agent reads. Re-run the install command any time to pull the latest rules.`,
        dependencies: [],
        registryDependencies: [],
        files: files.map((f) => ({
          path: f.path,
          type: 'registry:file',
          target: `~/${f.path}`,
          content: f.content,
        })),
      },
      null,
      2,
    ) + '\n',
  )
  brainTeasers[slug] = teaser
  brainSlugs.push(slug)
  log(`bundled brain "${slug}": ${files.length} file(s) → registry-data/_${slug}-brain.json + servable ${slug}-brain.json`)
}
writeBrainTeaser(BRAIN_TEASER_MODULE, brainTeasers['andromeda'] ?? null)
writeBrainTeaser(BRAIN_TEASER_PRO_MODULE, brainTeasers['andromeda-pro'] ?? null)

// ── 5. _premium.json — feeds the /r gate's premiumSlugs ────────────────────
// `standalones` feeds premiumSlugs exactly as before; `freeSystemComponents`
// lists the injected FREE v2 file paths and `brains` the bundled brain slugs so
// downstream scripts (leak guard, health checks) can see what was injected.
writeFileSync(
  PREMIUM_JSON,
  JSON.stringify(
    { standalones: manifestSlugs, freeSystemComponents: freePaths, brains: brainSlugs },
    null,
    2,
  ) + '\n',
)

// ── 6. Registration shim (gitignored) ──────────────────────────────────────
const ident = (s) => 'C_' + s.replace(/[^a-z0-9]/gi, '_')
const imports = [
  '// AUTO-GENERATED by scripts/inject-premium.mjs — gitignored, never committed.',
  "import dynamic from 'next/dynamic'",
  "import type { ComponentEntry } from './component-registry'",
  "import { componentCodes } from './component-codes.generated'",
]
const decls = []
const entries = []
for (const { slug, meta, hasPrompts } of injected) {
  const v = ident(slug)
  if (hasPrompts) imports.push(`import { prompts as ${v}_p } from '../../components-workspace-premium/${slug}/prompts'`)
  decls.push(`const ${v} = dynamic(() => import('../../components-workspace-premium/${slug}'))`)
  const tags = JSON.stringify(meta.tags ?? [{ label: 'Cards', accent: true }])
  entries.push(
    '  {\n' +
      `    slug: ${JSON.stringify(slug)},\n` +
      `    name: ${JSON.stringify(meta.name)},\n` +
      `    description: ${JSON.stringify(meta.description)},\n` +
      `    tags: ${tags},\n` +
      (meta.image ? `    image: ${JSON.stringify(meta.image)},\n` : '') +
      (meta.dualTheme ? '    dualTheme: true,\n' : '') +
      (meta.staticPreview ? '    staticPreview: true,\n' : '') +
      (meta.isBlock ? '    isBlock: true,\n' : '') +
      `    badge: 'Premium',\n` +
      `    PreviewComponent: ${v},\n` +
      `    code: componentCodes[${JSON.stringify(slug)}] ?? '',\n` +
      `    prompts: ${hasPrompts ? `${v}_p` : '{}'},\n` +
      '  },',
  )
}
const shim = [...imports, '', ...decls, '', 'export const PREMIUM_COMPONENTS: ComponentEntry[] = [', ...entries, ']', ''].join('\n')
writeFileSync(SHIM, shim)

writeBuildInfo(builtSha)

if (tmpClone) rmSync(tmpClone, { recursive: true, force: true })
log(
  `injected ${injected.length} premium component(s): ${injected.map((i) => i.slug).join(', ')}` +
    (builtSha ? ` @ ${builtSha.slice(0, 7)}` : ''),
)
